# Generated by Django 3.0.2 on 2020-01-29 01:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_auto_20200128_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sumary',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
